c0c0n3/kitt4sme.live

deployment/mesh-infra/argocd/projects/mesh-infra/keycloak/app.yaml, deployment/mesh-infra/argocd/projects/mesh-infra/keycloak/kustomization.yaml, deployment/mesh-infra/argocd/projects/mesh-infra/kustomization.yaml, deployment/mesh-infra/argocd/projects/mesh-infra/storage/app.yaml, deployment/mesh-infra/argocd/projects/mesh-infra/storage/kustomization.yaml, deployment/mesh-infra/keycloak/base.yaml, deployment/mesh-infra/keycloak/kustomization.yaml, deployment/mesh-infra/kustomization.yaml, deployment/mesh-infra/routing/ingress.yaml, deployment/mesh-infra/storage/keycloak.yaml, deployment/mesh-infra/storage/kustomization.yaml
This PR implements basic Keycloak deployment to the KITT4SME live cluster as requested by #9.
We implemented the following features:
- Basic manifests to run Keycloak in a K8s cluster. Keycloak runs in standalone HA mode so it's possible to scale it going forward.
- Keycloak persistence. Keycloak is configured with H2 as a backing database. The DB instance is embedded in Keycloak so if we want to scale Keycloak we've got to replace H2 with an external DB---e.g. Postgres. But that's an easy thing to do, so for now we're going to keep it simple.
- Physical storage. H2 writes its DB files to `/opt/jboss/keycloak/standalone/data` so we mount this dir on a K8s volume backed by 1GB physical storage.
- Keycloak master realm admin. We don't provide one by default so there's no master admin …
=> Basic Keycloak deployment

deployment/mesh-infra/argocd/projects/plat-infra-services/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-infra-services/opcua-agent-supsi/app.yaml, deployment/mesh-infra/argocd/projects/plat-infra-services/opcua-agent-supsi/kustomization.yaml, deployment/plat-infra-services/kustomization.yaml, deployment/plat-infra-services/opcua-agent-supsi/base.yaml, deployment/plat-infra-services/opcua-agent-supsi/config.json, deployment/plat-infra-services/opcua-agent-supsi/config.properties, deployment/plat-infra-services/opcua-agent-supsi/kustomization.yaml
This PR implements a fully fledged OPC UA agent service to be used by SUPSI. Specifically, the following got implemented.
* Manifests to run the OPC UA agent in a K8s cluster.
* In-memory configuration. The service pre-loads device mappings and other config in memory to speed up OPC UA to FIWARE data translation.
* Persistence. No Mongo DB backend. Data sits in memory (it isn't much actually) but it's loaded from K8s configmaps, so that's the persistence backend. (If the pod restarts, config map data gets loaded again in memory; all service pods share the same config map data.) 
* IaC management. The manifests of all agent-related resources are tied to an Argo CD app in the mesh infra project so we can easily manage deployments through a GUI too.
* Simplified config model. All the agent …
=> SUPSI OPC UA agent

deployment/mesh-infra/storage/crate.yaml, deployment/mesh-infra/storage/kustomization.yaml, deployment/plat-infra-services/cratedb/base.yaml
We deployed Crate during the Nov 2021 demo sprint. But some bits and pieces were still missing and some improvements were needed. This PR completes the work we started in Nov 2021.
* Physical storage. Crate writes its DB files to `/data` so we mount this dir on a K8s volume backed by 10GB physical storage. That should be enough disk space for the next few months but we'll probably have to up it as soon as we connect real-world devices. (Consider we've only got 120GB physical storage at the moment and other DBs to cater for, so it's best not to allocate too much storage until we expand our underlying physical capacity.)
* Security. You can't access Crate directly from outside the cluster anymore. So e.g. you won't be able to browse to `kitt4sme.collab-cloud.eu:4200` and get into the admin …
=> Complete CrateDB deployment

deployment/mesh-infra/argocd/argocd-server.yaml, deployment/mesh-infra/argocd/kustomization.yaml
This PR fixes #111.
The reason for not being able to log in to Argo CD with Keycloak was that the OIDC client secret had changed in Keycloak. Even though the  `argocd-secret` was updated with the new OIDC client secret value, Argo CD Server didn't pick it up so it was still using the old OIDC client secret value. So Keycloak would deny access.
We now use Reloader to bounce Argo CD Server whenever `argocd-secret` changes.
=> Bounce Argo CD Server on secret config change

deployment/mesh-infra/security/ingress-policy.yaml, deployment/plat-infra-services/quantumleap/base.yaml
This PR changes some settings to make sure we can demo our apps at the GA without trouble:
- let external clients call Orion without a security token
- upgrade to Quantum Leap 0.8.3---the previous version won't work w/ the newly developed [dashboards][dazzler]
[dazzler]: https://github.com/c0c0n3/kitt4sme.dazzler
=> GA demo preps

deployment/mesh-infra/argocd/projects/plat-app-services/dazzler/app.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/dazzler/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/kustomization.yaml, deployment/mesh-infra/routing/ingress.yaml, deployment/mesh-infra/security/ingress-policy.yaml, deployment/plat-app-services/dazzler/base.yaml, deployment/plat-app-services/dazzler/kustomization.yaml
This PR implements a basic [Dazzler][dazzler] deployment. Features:
* General purpose, multi-tenant, Dash-powered dashboards.
* VIQE inspection dashboard.
* Roughnator surface roughness estimate dashboard.
* IaC. Dazzler manifests are tied to an Argo CD app in the mesh infra project so we can easily manage deployments through a GUI too.
* Security. Even though this PR doesn't implement security, it can easily be bolted on top since dashboard routes include the tenant name. So we can easily apply an OPA policy similar to the one we've implemented for the FIWARE services. Once that's in place, we can restrict access to the Dazzler service to requests containing a valid Keycloak token.
[dazzler]: https://github.com/c0c0n3/kitt4sme.dazzler
=> Basic Dazzler deployment

README.md, deployment/mesh-infra/security/kustomization.yaml, nix/kubeseal.nix
This PR upgrades our Sealed Secret setup from version `0.17.3` to `0.17.5`. This is a hot-fix for the open call devs since version `0.17.3` is unstable and shouldn't be used anymore.
See:
- #144 
- #147
=> Upgrade Sealed Secrets

deployment/mesh-infra/argocd/projects/plat-app-services/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/workerpro/app.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/workerpro/kustomization.yaml, deployment/plat-app-services/kustomization.yaml, deployment/plat-app-services/workerpro/base.yaml, deployment/plat-app-services/workerpro/kustomization.yaml, dev/workerpro/docker-compose.yml
This PR implements a basic Worker Profiler deployment.
* K8s manifests to run the Worker Profiler service in the Kitt4sme cloud.
* IaC. Worker Profiler manifests are tied to an Argo CD app in the mesh infra project so we can easily manage deployments through a GUI too.
* Routing. The service is exposed to clients outside the cluster through a K8s node port (`7777`). This isn't optimal, but see #151 about it.
* Storage. The service connects to the existing Postgres instance in the platform infra service layer.
* Security. The password to connect to the DB is encrypted in a sealed secret rather than being plain text in the K8s manifest. For the rest, there's no security at the moment, anyone with the right URL can access the service. We'll secure the service later, see #153.
* Test env. …
=> Worker Profiler deployment

deployment/mesh-infra/argocd/projects/plat-app-services/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/sads/app.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/sads/kustomization.yaml, deployment/mesh-infra/routing/ingress.yaml, deployment/mesh-infra/security/ingress-policy.yaml, deployment/plat-app-services/sads/base.yaml, deployment/plat-app-services/sads/kustomization.yaml, dev/sads/docker-compose.yml
This PR implements a basic SADS deployment.
* K8s manifests to run the SADS service in the Kitt4sme cloud.
* IaC. SADS manifests are tied to an Argo CD app in the mesh infra project so we can easily manage deployments through a GUI too.
* Routing. The service is exposed to clients outside the cluster through Istio path-based routing. Endpoint: `<cloud-url>/sads/`, e.g. http://kitt4sme.collab-cloud.eu/sads/.
* Security. There's no security at the moment, anyone with the right URL can access the service. We'll secure the service later, see #160.
* Test env. There's a Docker Compose file in `dev/sads` you can use for testing the service locally. It comes with a setup close to what we have in the cloud. Also keep in mind, using the [Flaw Sleuth][flaw-sleuth] simulator is usually easier. …
=> Basic SADS cloud deployment

deployment/mesh-infra/argocd/projects/plat-app-services/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/viqe/app.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/viqe/kustomization.yaml, deployment/mesh-infra/routing/ingress.yaml, deployment/mesh-infra/security/ingress-policy.yaml, deployment/plat-app-services/viqe/base.yaml, deployment/plat-app-services/viqe/kustomization.yaml
This PR implements a basic VIQE cloud service deployment.
* K8s manifests to run the VIQE service in the Kitt4sme cloud.
* IaC. SADS manifests are tied to an Argo CD app in the mesh infra project so we can easily manage deployments through a GUI too.
* Routing. The service is exposed to clients outside the cluster through Istio path-based routing. Endpoint: `<cloud-url>/viqe/`, e.g. http://kitt4sme.collab-cloud.eu/viqe/.
* Security. There's no security at the moment, anyone with the right URL can access the service. We'll secure the service later, see #163.
* Test env. Using the various environment in the [service repo][viqe].
[viqe]: https://github.com/c0c0n3/kitt4sme.viqe
=> Basic VIQE deployment

deployment/plat-app-services/dazzler/base.yaml, deployment/plat-app-services/dazzler/dazzler-config.yaml, deployment/plat-app-services/dazzler/kustomization.yaml
This PR upgrades Dazzler to version `0.3.0` which includes the new VIQE dashboards. Istio routing and security haven't changed. The dashboards that got wired in for this deployment are:
- Roughnator. Same as before. Available at `<cloud base url>/dazzler/csic/-/roughnator`.
- VIQE raw materials. New VIQE dashboard for raw materials inspection to be used in the Hand Tools field trial. Available at `<cloud base url>/dazzler/itek/-/raw_materials`.
- VIQE tweezers. New VIQE dashboard for tweezers inspection to be used in the Hand Tools field trial. Available at `<cloud base url>/dazzler/itek/-/tweezers`
=> Refresh Dazzler deployment

nix/flake.lock, nix/flake.nix
This PR fixes #167 by fetching kubeseal `0.17.5` from Nixpkgs `22.05`.
Ideally we'd build kubeseal off Nixpkgs `21.11`, our main package source at the moment. In fact, that'd save quite a bit of build time and almost 4GB space in the Nix store---on MacOS. That's why we whipped together our own `kubeseal.nix` recipe. But it looks like we did it too quickly, as it breaks on some Linux flavours---see #167, #166, #144.
A better option would be to upgrade the whole mesh infra since it's about two years old. That means we could also easily switch to the latest Nixpkgs where all the tools we need are there and actually work. But for the time being we put in place this stopgap solution to help all the peeps out there who got stuck on this issue.
=> Fix broken kubeseal package

deployment/mesh-infra/argocd/projects/plat-app-services/fams/app.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/fams/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/kustomization.yaml, deployment/mesh-infra/security/secrets/fams-image.sh, deployment/mesh-infra/security/secrets/fams-image.yaml, deployment/mesh-infra/security/secrets/kustomization.yaml, deployment/plat-app-services/fams/base.yaml, deployment/plat-app-services/fams/kustomization.yaml, deployment/plat-app-services/kustomization.yaml
This PR implements a basic Fatigue Monitoring System (FAMS) deployment.
* K8s manifests to run the FAMS service in the Kitt4sme cloud.
* IaC. FAMS manifests are tied to an Argo CD app in the mesh infra project so we can easily manage deployments through a GUI too.
* Security. The FAMS image is private and K8s pulls it through a Docker secret. We manage the secret the usual way with Sealed Secrets and Reloader. So the actual Docker secret is never stored in this repo, what gets stored here is the Sealed Secret encrypting the data that makes up the Docker secret. We whipped together a script to generate the Sealed Secret from a GitLab Access Token containing a permission to pull the image.
* Docs. How to use sealed secrets/reloader for docker image secrets. (Security Ops page.)
1. Service …
=> Basic Fatigue Monitoring System deployment

deployment/mesh-infra/storage/kustomization.yaml, deployment/mesh-infra/storage/mongo.yaml, deployment/plat-infra-services/mongodb/base.yaml
This PR implements a basic Mongo DB persistent storage as requested by #5.
Features:
* Physical storage. We make Mongo DB write its DB files to /data/db and mount this dir on a K8s volume backed by 10GB physical storage. That should be enough disk space for the next few months but we'll probably have to up it as soon as we connect real-world devices. (Consider we've only got 120GB physical storage at the moment and other DBs to cater for, so it's best not to allocate too much storage until we expand our underlying physical capacity.)
=> Mongo DB storage

deployment/mesh-infra/argocd/projects/plat-infra-services/json-agent/app.yaml, deployment/mesh-infra/argocd/projects/plat-infra-services/json-agent/kustomization.yaml, deployment/mesh-infra/argocd/projects/plat-infra-services/kustomization.yaml, deployment/mesh-infra/routing/ingress.yaml, deployment/plat-infra-services/json-agent/base.yaml, deployment/plat-infra-services/json-agent/config.js, deployment/plat-infra-services/json-agent/kustomization.yaml, deployment/plat-infra-services/kustomization.yaml
This PR implements a fully-fledged JSON Agent deployment with HTTP and MQTT transports as #185 requested. Specifically, the following got implemented.
* Manifests to run JSON Agent in a K8s cluster. The agent comes with an internal endpoint for provisioning and two external endpoints to get JSON device data in, one over HTTP, the other over MQTT---see #181 for our current MQTT setup.
* Routing. We expose the HTTP endpoint at `<kitt4sme-base-url>/jsonagent/` so devices can POST JSON data at `<kitt4sme-base-url>/jsonagent/iot/json?k=<api-key>&i=<device-id>`. To send JSON data over MQTT, devices use the MQTT WebSocket implemented in #181 and the topic: `json/<api-key>/<device-id>/attrs`.
* Security. Istio handles TLS termination for the HTTP endpoint and delegates security decisions to the …
=> JSON Agent

deployment/mesh-infra/security/ingress-policy.yaml
http://kitt4sme.collab-cloud.eu/datasheets/
http://kitt4sme.collab-cloud.eu/datasheets-backend-rest/
Hi, I think this should be included to expose both of the endpoints above.
=> Digital Datasheets deployment continuation 

deployment/mesh-infra/routing/ingress.yaml
reouting ingress.yaml file has been updated to include TLS and nonsecure rerouting is set to false so insecure URL's should still work. New routing has to be deployed and kubernetes secret creates as per: [Secure external HTTP traffic#77](https://github.com/c0c0n3/kitt4sme.live/issues/77)
Server certificates are at /etc/certs (server.key and server.crt)
=> Enabled TLS, not tested, need to still create secrets on cluster

deployment/mesh-infra/argocd/argocd-cm.yaml
This PR undoes #209. Even though we now have proper SSL certs, our version of Argo CD can't validate them---see #210 about it. So for now we implement a stopgap solution which will let us access ArgoCD over HTTP---yea, massive security liability right there, but hey, we still don't have any real data in the collab cloud instance.
In detail
- The Argo CD config map (`argocd-cm`) specifies plain HTTP URLs for both the ArgoCD and Keycloak endpoints.
- The Argo CD OIDC client in the Keycloak master realm specifies plain HTTP URLs for all the ArgoCD endpoints.
- The Keycloak master realm login settings have `Require SSL: none`
As soon as #210 is implemented we can ditch this stopgap solution by restoring HTTPs across the board (`argocd-cm`, OIDC client) and setting `Require SSL: all requests`
=> Rollback #209

deployment/plat-app-services/profilers/base.yaml
This change should resolve the issue, the site should be accessible from "kitt4sme.collab-cloud.eu:8080/"
=> Port mapping issue

deployment/plat-app-services/aq/base.yaml
This PR improves the basic Adaptive Questionnaire deployment of #217.
- AQ got upgraded to version `1.6.3` which includes some bug fixes, most notably https://github.com/IDSIA/adapquest/issues/25. This fix enables us to use URL path based routing.
- Routing. We ditched the node port setup of #217 and are now using the usual path-based approach, implementing a URL-path route `/aq` to deliver external HTTP requests to the AQ service.
- Istio sidecar. This PR puts back the Istio sidecar that #217 removed. In fact, #216 isn't an issue anymore with URL-path routes.
=> Adaptive Questionnaire path-based routing

deployment/mesh-infra/argocd/kustomization.yaml
Updated ArgoCD to 2.4.0 and tested with local deployment of the cluster. Seemed to work just fine, but later synced agains main branch and revert back to 2.2.5. I didn't fork the repo so I think that behavior is expected and the change is OK.
=> updated argocd to 2.4.0 version to fix SSL issue

deployment/mesh-infra/argocd/kustomization.yaml
Reverts c0c0n3/kitt4sme.live#215 didn't seem to work as planned after all... well back to the drawing board.
=> Revert "updated argocd to 2.4.0 version to fix SSL issue"

deployment/mesh-infra/argocd/argocd-cm.yaml, deployment/mesh-infra/argocd/kustomization.yaml, docs/security.md
This PR hopefully puts an end to the Argo CD SSO saga. Here's how.
- HTTPs. Updated Argo CD configuration to use HTTPs when performing the OIDC code grant flow. This is because as of #207, we have a proper TLS certificate, so we can use HTTPs instead of plain HTTP.
- Keycloak. Reconfigured Argo CD OIDC client in the `master` realm to use HTTPs. Also both `master` and `kitt4sme` realms now only accept HTTPs connections---i.e. in the login config of both realms, "Require SSL" is set to "all requests".
- TLS cert. Added `*.collab-cloud.eu` cert to the ones Argo CD trusts.
- Server version. Downgraded from `2.7.0-rc1` to latest official release (`2.6.7`) as `2.7.0` is a pre-release still actively being worked on.
With these fixes in place, you can now log into Argo CD through Keycloak over …
=> Argo CD SSO fixes

deployment/plat-app-services/aq/base.yaml
This PR upgrades Adaptive Questionnaire to version `1.6.4` and customises it with
- A title of "KITT4SME Adaptive Questionnaire"
- A button to find a suitable kit in the RAMP marketplace. At the end of the survey, Adaptive Questionnaire displays a "find a kit for your needs" button. When the user click on the button the browser gets redirected to https://ramp.eu/?sid=xxx, where `xxx` is the survey's session ID. This allows RAMP to pass on the session ID to Platform Configurator which can then get hold of the survey data in the Postgres DB.
Notice the RAMP URL will most likely have to be reconfigured (`ADAPQUEST_EXIT_URL` env var) after this PR since at this stage we still don't know what the RAMP endpoint is that will process KITT4SME AQ surveys.
=> AQ customisation

deployment/mesh-infra/routing/ingress.yaml
This PR makes SADS "offline" available to external clients at `https://<cloud-host>/sads-offline`, fixing #238.
The SADS "offline" routing rule must come before the one for SADS classic. This is because we're using a prefix match
in both cases: `/sads-offline` and `/sads`. So if we invert the order, both routes will hit SADS classic---see #238. Why not use a regex match? In principle it's a better option since it avoids reliance on Istio match order, which is a bit of a hack.
For example,
```yaml
- match:
- uri:
regex: /(sads$|sads[^-])
```
should match `/sads`, `/sads/`, `/sads/wada-wada` but not `/sads-offline`. Unfortunately, that regex doesn't work with Istio `1.11.4`. Hence the hack.
=> Fix SADS offline route

deployment/mesh-infra/routing/ingress.yaml, deployment/mesh-infra/security/secrets/kustomization.yaml, deployment/mesh-infra/security/secrets/platform-configurator-image.sh, deployment/mesh-infra/security/secrets/platform-configurator-image.yaml, deployment/plat-app-services/kustomization.yaml, deployment/plat-app-services/platform-configurator/base.yaml, deployment/plat-app-services/platform-configurator/kustomization.yaml
This pull request deploys the Platform Configurator to the KITT4SME Platform.
The Docker image is available in SUPSI's GItlab Registry, which is private. This requires to re-generate the sealed secret with a new token provided by SUPSI.
=> Platform configurator deployment

deployment/plat-app-services/platform-configurator/base.yaml
This PR refreshes the Platform Configurator image to the latest version (`0.1.0`) and adds a "RAMP_KITS_URL" to configure the RAMP endpoint to call to pass on a kit configuration.
=> Platform Configurator deployment refresh

deployment/plat-app-services/dazzler/base.yaml, deployment/plat-app-services/dazzler/dazzler-config.yaml
This PR upgrades Dazzler to version `0.5.0` and enables the FAMS dashboard for the "demo" tenant.
=> FAMS dashboard

deployment/mesh-infra/security/secrets/api-keys.yaml, deployment/mesh-infra/security/secrets/kustomization.yaml, deployment/mesh-infra/security/secrets/templates/api-keys.yaml, deployment/plat-app-services/platform-configurator/base.yaml
This PR refreshes Platform Configurator (v0.3.0)
Compared with v0.2.0:
- Kits are posted directly to "RAMP kits service" (RAMP_KITS_SVC_URL)
- The endpoint /kits-ramp redirects to a new page, based on the RAMP_REDIRECT_URL env var. The redirect includes "sid" as a query parameter
- Missing fields in datasheets are properly handled
- Exceptions while contacting RAMP are caught, but still not handled
Before going live, it is needed to create a new secret (name: **api-keys**, key: **pc.ramp.kits.svc**)
=> Update PC (v0.3.0)

deployment/plat-app-services/dazzler/base.yaml
This PR deploys the latest Dazzler version (`0.6.0`) which fixes some issues with the FAMS dashboard:
- https://github.com/c0c0n3/kitt4sme.dazzler/pull/10
=> Deploy latest dazzler (0.6.0)

deployment/plat-app-services/platform-configurator/base.yaml
This PR patches the Platform Configurator, which now does not consider tool's dependencies with unknown UUIDs (i.e., dependencies pointing to UUID not available in the datasheets database)
=> Patch Platform Configurator

deployment/mesh-infra/routing/ingress.yaml, deployment/plat-app-services/sads/base.yaml
This PR updates SADS to version `0.3.0` so we can take advantage of @souayb's revamped implementation.
See
- https://github.com/c0c0n3/kitt4sme.flaw-sleuth/pull/7
=> SADS refresh

deployment/plat-app-services/fams/base.yaml
This version updates FaMS to the lastest version.
This version fixes some bugs related to the download of dynamic data (from QL) of active workers (i.e., workers with an active session, wearing a device).
=> Update fams version (0.2.3)

deployment/plat-app-services/platform-configurator/base.yaml
This PR updated Platform Configurator to version `0.4.1` and makes it redirect the user to the RAMP service request endpoint after the user clicks the "find a kit" button in Adaptive Questionnaire. At the moment we configured PC to append the AQ session ID to the redirect URL before issuing the redirect response to the broswer.
=> Platform Configurator RAMP redirect

deployment/plat-app-services/dazzler/base.yaml
This PR upgrades Dazzler to version `0.7.0` which comes with a revamped FAMS dashboard:
- https://github.com/c0c0n3/kitt4sme.dazzler/pull/11
=> Upgrade Dazzler to v0.7.0

deployment/plat-app-services/im/base.yaml
This PR refreshes IM with the latest version that properly handles the servlet context path (i.e., /intervention-manager), also while displaying forms in the Tasklist page.
This allows us to use a proper routing for accessing the server, instead of resorting to using node ports.
=> refresh IM to v1.0.4-k4s

deployment/mesh-infra/argocd/projects/plat-app-services/static-page/app.yaml, deployment/mesh-infra/argocd/projects/plat-app-services/static-page/kustomization.yaml
I needed to create a multipass instance with a larger disk space so decided to start from scratch found an error when running this command:
`$ kustomize build \
https://github.com/c0c0n3/kitt4sme.live/deployment/mesh-infra/argocd | \
kubectl apply -f -`
And found that the static page was missing the code from argocd directory.
=> Found an issue when building the cluster locally

deployment/mesh-infra/routing/ingress.yaml
Two commits one outlines all the endpoints that should be available then the second is a simplified version of this, please think about how this code could affect things in a bigger picture.
The static page is now accessible via  "/" and the "/static-page"
https://kitt4sme.collab-cloud.eu/
https://kitt4sme.collab-cloud.eu/static-page/
Once merged I will create a ticket to remove the https://kitt4sme.collab-cloud.eu/static-page/
=> Static page url

deployment/plat-app-services/platform-configurator/base.yaml
Update platform configurator to v0.5.0
The new version uses new DTOs to meet RAMP APIs.
Also, adding the arg "--root-path /platform-configurator" to the deployment should solve the issue discussed in #273 (the tool documentation will be available at /platform-configurator/docs).
=> Update platform configurator

deployment/plat-app-services/sads/base.yaml
This PR upgrades SADS to version `0.4.0` so we can enjoy some bug fixes:
- https://github.com/c0c0n3/kitt4sme.flaw-sleuth/issues/12
- https://github.com/c0c0n3/kitt4sme.flaw-sleuth/pull/13
=> Upgrade SADS to version 0.4.0

deployment/mesh-infra/routing/ingress.yaml, deployment/plat-app-services/sads-offline/base.yaml, deployment/plat-app-services/sads/base.yaml
This PR make the SADS "offline" service the only SADS service accessible to external users.
In detail:
- SADS "online" is now set to have no replicas. The deployment descriptors are still there, but there's no service running in the cluster. Ditto for the Argo CD app---we keep it around just in case.
- SADS "offline" now handles all incoming requests to the `/sads` path.
- The `/sads-offline` path is unavailable.
- Wamtechnik will have to change the URL they use to access SADS "offline". After this PR gets merged, they'll have to use "https://kitt4sme.collab-cloud.eu/sads/" instead of the current URL of "https://kitt4sme.collab-cloud.eu/sads-offline/".
- The "static page" (home) needs to be updated as well to reflect the URL change.
=> SADS switchover

deployment/plat-app-services/platform-configurator/base.yaml
hotfix - Change the platform configurator config to avoid the exception "urllib3.exceptions.LocationValueError: No host specified."
=> hotfix - update platform configurator config

deployment/mesh-infra/routing/ingress.yaml
We should test this. after merging profilers should be available at https://profilers.kitt4sme.collab-cloud.eu
=> added subdomain route for profilers

deployment/mesh-infra/routing/ingress.yaml
Moved abovementioned components to subdomains. Components need to be tested individually for functionality. Just a heads up for reviewers as this testing can not be really performed until the PR has been merged and deployed in production.
=> moved SADS, AQ, Optiplant and Platform-Configurator to subdomains

deployment/mesh-infra/routing/ingress.yaml
For some reason SADS block -authority: didn't compute and match section was translated to just {}
=> try to fix YAML problem in SADS routing

deployment/plat-app-services/platform-configurator/base.yaml
The new version patches an error occurring when datasheets don't have a specified version (field information.version empty), or specify dependencies without a proper module ID
=> update platform configurator (v0.8.0)

deployment/plat-app-services/datasheets/frontend.yaml
The datasheets tool fails to load showing many errors related to resources not found at /datasheets/...
This might be due to the new platform deployment based on subdomains. This PR update the root path for the datasheets frontend.
=> Fix Datasheets

deployment/mesh-infra/routing/ingress.yaml
to add backward compatibility for dazzler
=> Update ingress.yaml to have dazzler both in path and subdomain

deployment/plat-app-services/dazzler/base.yaml, deployment/plat-app-services/dazzler/dazzler-config.yaml
This PR upgrades Dazzler to version `0.9.0` so we can use the new Optiplant dashboard---see https://github.com/c0c0n3/kitt4sme.dazzler/pull/13. The dashboard is available from either URL below
- https://dazzler.kitt4sme.collab-cloud.eu/dazzler/optiplant/-/status/
- https://kitt4sme.collab-cloud.eu/dazzler/optiplant/-/status/
=> Optiplant dashboard
