c0c0n3/kitt4sme.live

vm/Vagrantfile, vm/config.yaml
This PR implements the Vagrant configuration for the platform VM to be used for open calls as requested by #65.
Contributed by @tassosgeo.
=> Vagrant VM configuration

deployment/plat-app-services/workerpro/base.yaml
Yep, this PR does exactly what the title says :-)
=> Expose Worker Profiler on port 8080 to work around firewall rules

README.md, docs/wp6-field-trials/README.md, docs/wp6-field-trials/electrical-equipment.md, docs/wp6-field-trials/fastener-sorting.md, docs/wp6-field-trials/hand-tools.md, docs/wp6-field-trials/injection-moulding.md, docs/wp6-field-trials/overview.md
This PR stashes away some notes about WP6 pilot deployments that we have in D2.7. This is just for extra convenience since online info is easier to browse and maintain.
=> Stash away notes about wp6 field trials

deployment/mesh-infra/keycloak/base.yaml
This PR is a port of @ds2268's fix to #175. Thanks for the fix @ds2268!
=> Explicitly set Keycloak DB backend

deployment/mesh-infra/routing/ingress.yaml, deployment/plat-app-services/profilers/base.yaml
Node port has been removed and port mapping has been created for the profiler.
=> Ingress file updated to use port mapping, base file node port removal

deployment/mesh-infra/routing/ingress.yaml, deployment/plat-app-services/profilers/base.yaml
Lets revert back to NodePort for now while we resolve the issue.
=> Issue with ingress port mapping

deployment/mesh-infra/argocd/kustomization.yaml
Tested locally, run "kustomize build . | kubectl apply -f -" and the refresh the page (control shift r) if required.
Upgraded the Argocd to version 2.7
=> Upgraded argocd from 2.2.5 to 2.7

deployment/plat-app-services/matchmaking/base.yaml, deployment/plat-app-services/matchmaking/base.yaml.bak, deployment/plat-app-services/matchmaking/kustomization.yaml, deployment/plat-app-services/matchmaking/kustomization.yaml.bak
Matchmaking tool pull request.
=> matchmaking tool added

deployment/plat-app-services/fams/base.yaml
This PR updates FAMS to version `0.2.0-ks`.
=> Update fams with new version 0.2.0-k4s

deployment/mesh-infra/routing/ingress.yaml
Reverts c0c0n3/kitt4sme.live#334
This should not have been merged as it blocks access to the other pages
=> Revert "Static page url"

deployment/plat-app-services/sads-offline/base.yaml
This PR upgrades SADS Offline to version 0.1.6 so we can enjoy the latest functionality upgrade.
=> Upgrade SADS-offline to version 0.1.6

deployment/mesh-infra/routing/ingress.yaml
As discussed in the GA change the routing from the /static-page/ to /home/
=> Update to static page routing

deployment/plat-app-services/optiplant/base.yaml, deployment/plat-app-services/optiplant/kustomization.yaml
=> Updated repo for Optiplant

deployment/plat-app-services/static-page/base.yaml
There has been updates to the static page so we have updated the docker image and now updating the image for the platform
=> Updated the static page image version

deployment/plat-app-services/datasheets/backend.yaml, deployment/plat-app-services/datasheets/frontend.yaml
Just waiting on confirmation from testing before deploying this.
=> DRAFT: Updates to the datasheets image and the database name

deployment/plat-app-services/platform-configurator/base.yaml
This pull request update Platform Configurator to the latest version. The latest version removes the dependency from the Datasheets Backend database by exploiting its REST API.
=> update platform configurator

deployment/mesh-infra/routing/ingress.yaml
use exact rather than contains in subdomain route
=> tweaked subdomain route for profilers

deployment/mesh-infra/routing/ingress.yaml
Some problem with YAML, lets see if this clarifies it
=> Subdomains patch1

deployment/mesh-infra/routing/ingress.yaml
Rest of the routed application layer solutions moved to subdomains
=> second patch of subdomains

deployment/plat-app-services/im/base.yaml
Update IM deployment (now using subdomains)
=> change context path (no path-based routing)

deployment/mesh-infra/routing/ingress.yaml
Updates to allow data sheets subdomain routing to work.
=> Datasheets front and backend subrouting

deployment/plat-app-services/dazzler/dazzler-config.yaml
Optioplant integration to Dazzler
=> Update dazzler-config.yaml for optiplant

deployment/plat-app-services/sads-offline/base.yaml
Reverts c0c0n3/kitt4sme.live#435 second try
=> Revert "removed sads -path from the SADS deployment files due to subdomain r…"

deployment/plat-app-services/sads-offline/base.yaml
As requested an updated version
=> Updates to enhance product

deployment/mesh-infra/routing/ingress.yaml, deployment/plat-app-services/gnosis/base.yaml
Update to the routing for application to be accessed via subdomains
=> Started the routing
